//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentaCar.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        public int Id { get; set; }
        [Required (ErrorMessage = "Kullanýcý Adýný Giriniz!")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Parolayý Giriniz!")]
        public string UserPassword { get; set; }
    }
}
